version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: recipeforadisaster_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: RecipeManagerDB
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init:/docker-entrypoint-initdb.d
    networks:
      - recipeforadisaster_network

  mongo-express:
    image: mongo-express:latest
    container_name: recipeforadisaster_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
    depends_on:
      - mongodb
    networks:
      - recipeforadisaster_network

  app:
    build: .
    container_name: recipeforadisaster_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:password@mongodb:27017/RecipeManagerDB?authSource=admin
    depends_on:
      - mongodb
    networks:
      - recipeforadisaster_network

volumes:
  mongodb_data:

networks:
  recipeforadisaster_network:
    driver: bridge