version: '3.8'

services:
  app:
    build: .
    container_name: recipeforadisaster_app
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./recipes.db:/app/recipes.db
    networks:
      - recipeforadisaster_network

networks:
  recipeforadisaster_network:
    driver: bridge